server:
  port: 8000
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761:eureka

spring:
  application:
    name: apigateway-server
  cloud:
    gateway:
      routes:
        - id: test1-service
          uri: http://localhost:9001
          predicates:
            - Path=/first-service/**
        - id: test2-service
          uri: http://localhost:9002
          predicates:
            - Path=/second-service/**
        - id: kafka-service
          uri: http://localhost:9003
          predicates:
            - Path=/kafka/**
